/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SermonService } from "../sermon.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SermonCreateInput } from "./SermonCreateInput";
import { Sermon } from "./Sermon";
import { SermonFindManyArgs } from "./SermonFindManyArgs";
import { SermonWhereUniqueInput } from "./SermonWhereUniqueInput";
import { SermonUpdateInput } from "./SermonUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SermonControllerBase {
  constructor(
    protected readonly service: SermonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sermon })
  @nestAccessControl.UseRoles({
    resource: "Sermon",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSermon(@common.Body() data: SermonCreateInput): Promise<Sermon> {
    return await this.service.createSermon({
      data: data,
      select: {
        createdAt: true,
        date: true,
        description: true,
        id: true,
        mediaUrl: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Sermon] })
  @ApiNestedQuery(SermonFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Sermon",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sermons(@common.Req() request: Request): Promise<Sermon[]> {
    const args = plainToClass(SermonFindManyArgs, request.query);
    return this.service.sermons({
      ...args,
      select: {
        createdAt: true,
        date: true,
        description: true,
        id: true,
        mediaUrl: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sermon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sermon",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sermon(
    @common.Param() params: SermonWhereUniqueInput
  ): Promise<Sermon | null> {
    const result = await this.service.sermon({
      where: params,
      select: {
        createdAt: true,
        date: true,
        description: true,
        id: true,
        mediaUrl: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sermon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sermon",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSermon(
    @common.Param() params: SermonWhereUniqueInput,
    @common.Body() data: SermonUpdateInput
  ): Promise<Sermon | null> {
    try {
      return await this.service.updateSermon({
        where: params,
        data: data,
        select: {
          createdAt: true,
          date: true,
          description: true,
          id: true,
          mediaUrl: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sermon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sermon",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSermon(
    @common.Param() params: SermonWhereUniqueInput
  ): Promise<Sermon | null> {
    try {
      return await this.service.deleteSermon({
        where: params,
        select: {
          createdAt: true,
          date: true,
          description: true,
          id: true,
          mediaUrl: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
