/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ChurchInfoService } from "../churchInfo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ChurchInfoCreateInput } from "./ChurchInfoCreateInput";
import { ChurchInfo } from "./ChurchInfo";
import { ChurchInfoFindManyArgs } from "./ChurchInfoFindManyArgs";
import { ChurchInfoWhereUniqueInput } from "./ChurchInfoWhereUniqueInput";
import { ChurchInfoUpdateInput } from "./ChurchInfoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ChurchInfoControllerBase {
  constructor(
    protected readonly service: ChurchInfoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ChurchInfo })
  @nestAccessControl.UseRoles({
    resource: "ChurchInfo",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createChurchInfo(
    @common.Body() data: ChurchInfoCreateInput
  ): Promise<ChurchInfo> {
    return await this.service.createChurchInfo({
      data: data,
      select: {
        createdAt: true,
        description: true,
        foundedDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ChurchInfo] })
  @ApiNestedQuery(ChurchInfoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ChurchInfo",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async churchInfos(@common.Req() request: Request): Promise<ChurchInfo[]> {
    const args = plainToClass(ChurchInfoFindManyArgs, request.query);
    return this.service.churchInfos({
      ...args,
      select: {
        createdAt: true,
        description: true,
        foundedDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ChurchInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ChurchInfo",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async churchInfo(
    @common.Param() params: ChurchInfoWhereUniqueInput
  ): Promise<ChurchInfo | null> {
    const result = await this.service.churchInfo({
      where: params,
      select: {
        createdAt: true,
        description: true,
        foundedDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ChurchInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ChurchInfo",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateChurchInfo(
    @common.Param() params: ChurchInfoWhereUniqueInput,
    @common.Body() data: ChurchInfoUpdateInput
  ): Promise<ChurchInfo | null> {
    try {
      return await this.service.updateChurchInfo({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          foundedDate: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ChurchInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ChurchInfo",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteChurchInfo(
    @common.Param() params: ChurchInfoWhereUniqueInput
  ): Promise<ChurchInfo | null> {
    try {
      return await this.service.deleteChurchInfo({
        where: params,
        select: {
          createdAt: true,
          description: true,
          foundedDate: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
