/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WelcomeMessageService } from "../welcomeMessage.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WelcomeMessageCreateInput } from "./WelcomeMessageCreateInput";
import { WelcomeMessage } from "./WelcomeMessage";
import { WelcomeMessageFindManyArgs } from "./WelcomeMessageFindManyArgs";
import { WelcomeMessageWhereUniqueInput } from "./WelcomeMessageWhereUniqueInput";
import { WelcomeMessageUpdateInput } from "./WelcomeMessageUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WelcomeMessageControllerBase {
  constructor(
    protected readonly service: WelcomeMessageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WelcomeMessage })
  @nestAccessControl.UseRoles({
    resource: "WelcomeMessage",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWelcomeMessage(
    @common.Body() data: WelcomeMessageCreateInput
  ): Promise<WelcomeMessage> {
    return await this.service.createWelcomeMessage({
      data: data,
      select: {
        createdAt: true,
        id: true,
        messageText: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WelcomeMessage] })
  @ApiNestedQuery(WelcomeMessageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WelcomeMessage",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async welcomeMessages(
    @common.Req() request: Request
  ): Promise<WelcomeMessage[]> {
    const args = plainToClass(WelcomeMessageFindManyArgs, request.query);
    return this.service.welcomeMessages({
      ...args,
      select: {
        createdAt: true,
        id: true,
        messageText: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WelcomeMessage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WelcomeMessage",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async welcomeMessage(
    @common.Param() params: WelcomeMessageWhereUniqueInput
  ): Promise<WelcomeMessage | null> {
    const result = await this.service.welcomeMessage({
      where: params,
      select: {
        createdAt: true,
        id: true,
        messageText: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WelcomeMessage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WelcomeMessage",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWelcomeMessage(
    @common.Param() params: WelcomeMessageWhereUniqueInput,
    @common.Body() data: WelcomeMessageUpdateInput
  ): Promise<WelcomeMessage | null> {
    try {
      return await this.service.updateWelcomeMessage({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          messageText: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WelcomeMessage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WelcomeMessage",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWelcomeMessage(
    @common.Param() params: WelcomeMessageWhereUniqueInput
  ): Promise<WelcomeMessage | null> {
    try {
      return await this.service.deleteWelcomeMessage({
        where: params,
        select: {
          createdAt: true,
          id: true,
          messageText: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
