/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ContactFormSubmissionService } from "../contactFormSubmission.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ContactFormSubmissionCreateInput } from "./ContactFormSubmissionCreateInput";
import { ContactFormSubmission } from "./ContactFormSubmission";
import { ContactFormSubmissionFindManyArgs } from "./ContactFormSubmissionFindManyArgs";
import { ContactFormSubmissionWhereUniqueInput } from "./ContactFormSubmissionWhereUniqueInput";
import { ContactFormSubmissionUpdateInput } from "./ContactFormSubmissionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ContactFormSubmissionControllerBase {
  constructor(
    protected readonly service: ContactFormSubmissionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ContactFormSubmission })
  @nestAccessControl.UseRoles({
    resource: "ContactFormSubmission",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createContactFormSubmission(
    @common.Body() data: ContactFormSubmissionCreateInput
  ): Promise<ContactFormSubmission> {
    return await this.service.createContactFormSubmission({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        submittedAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ContactFormSubmission] })
  @ApiNestedQuery(ContactFormSubmissionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ContactFormSubmission",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async contactFormSubmissions(
    @common.Req() request: Request
  ): Promise<ContactFormSubmission[]> {
    const args = plainToClass(ContactFormSubmissionFindManyArgs, request.query);
    return this.service.contactFormSubmissions({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        submittedAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ContactFormSubmission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContactFormSubmission",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async contactFormSubmission(
    @common.Param() params: ContactFormSubmissionWhereUniqueInput
  ): Promise<ContactFormSubmission | null> {
    const result = await this.service.contactFormSubmission({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        submittedAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ContactFormSubmission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContactFormSubmission",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateContactFormSubmission(
    @common.Param() params: ContactFormSubmissionWhereUniqueInput,
    @common.Body() data: ContactFormSubmissionUpdateInput
  ): Promise<ContactFormSubmission | null> {
    try {
      return await this.service.updateContactFormSubmission({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          message: true,
          name: true,
          submittedAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ContactFormSubmission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContactFormSubmission",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteContactFormSubmission(
    @common.Param() params: ContactFormSubmissionWhereUniqueInput
  ): Promise<ContactFormSubmission | null> {
    try {
      return await this.service.deleteContactFormSubmission({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          message: true,
          name: true,
          submittedAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
