/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ServiceTimeService } from "../serviceTime.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ServiceTimeCreateInput } from "./ServiceTimeCreateInput";
import { ServiceTime } from "./ServiceTime";
import { ServiceTimeFindManyArgs } from "./ServiceTimeFindManyArgs";
import { ServiceTimeWhereUniqueInput } from "./ServiceTimeWhereUniqueInput";
import { ServiceTimeUpdateInput } from "./ServiceTimeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ServiceTimeControllerBase {
  constructor(
    protected readonly service: ServiceTimeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServiceTime })
  @nestAccessControl.UseRoles({
    resource: "ServiceTime",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createServiceTime(
    @common.Body() data: ServiceTimeCreateInput
  ): Promise<ServiceTime> {
    return await this.service.createServiceTime({
      data: data,
      select: {
        createdAt: true,
        day: true,
        id: true,
        time: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ServiceTime] })
  @ApiNestedQuery(ServiceTimeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ServiceTime",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceTimes(@common.Req() request: Request): Promise<ServiceTime[]> {
    const args = plainToClass(ServiceTimeFindManyArgs, request.query);
    return this.service.serviceTimes({
      ...args,
      select: {
        createdAt: true,
        day: true,
        id: true,
        time: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServiceTime })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceTime",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceTime(
    @common.Param() params: ServiceTimeWhereUniqueInput
  ): Promise<ServiceTime | null> {
    const result = await this.service.serviceTime({
      where: params,
      select: {
        createdAt: true,
        day: true,
        id: true,
        time: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServiceTime })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceTime",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateServiceTime(
    @common.Param() params: ServiceTimeWhereUniqueInput,
    @common.Body() data: ServiceTimeUpdateInput
  ): Promise<ServiceTime | null> {
    try {
      return await this.service.updateServiceTime({
        where: params,
        data: data,
        select: {
          createdAt: true,
          day: true,
          id: true,
          time: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServiceTime })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceTime",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteServiceTime(
    @common.Param() params: ServiceTimeWhereUniqueInput
  ): Promise<ServiceTime | null> {
    try {
      return await this.service.deleteServiceTime({
        where: params,
        select: {
          createdAt: true,
          day: true,
          id: true,
          time: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
